Fix for Innerloop test runs `kic test` (#44)
- Updated innerloop test run to execute load/integration tests for both `aioa` and `heartbeat`
- Update `--files` value for test runs on different nodeports
- convert ngsa-app to imdb-app
- update inner-loop to use imdb-app
- add probes
- update inner-loop dashboard to use imdb
- rename grafana groups

Co-authored-by: bartr <bartr@microsoft.com>

diff --git a/bin/.akdc/commands/cluster/deploy b/bin/.akdc/commands/cluster/deploy
--- a/bin/.akdc/commands/cluster/deploy
+++ b/bin/.akdc/commands/cluster/deploy
@@ -9,14 +9,14 @@
 # validate directories
 if [ ! -d ./deploy ]; then echo "./deploy directory not found. Please cd to an appropriate directory"; exit 1; fi
 if [ ! -d ./deploy/webv ]; then echo "./deploy/webv directory not found. Please cd to an appropriate directory"; exit 1; fi
-if [ ! -d ./deploy/aioa ]; then echo "./deploy/aioa directory not found. Please cd to an appropriate directory"; exit 1; fi
+if [ ! -d ./deploy/imdb ]; then echo "./deploy/imdb directory not found. Please cd to an appropriate directory"; exit 1; fi
 if [ ! -d ./deploy/bootstrap ]; then echo "./deploy/bootstrap directory not found. Please cd to an appropriate directory"; exit 1; fi
 
 # create namespace
 kubectl apply -f deploy
 
-# deploy ai-order-accuracy
-kubectl apply -f deploy/aioa
+# deploy imdb reference app
+kubectl apply -f deploy/imdb
 
 # deploy heartbeat, prometheus, grafana, and fluent bit
 kubectl apply -f deploy/bootstrap
@@ -25,7 +25,6 @@ kubectl apply -R -f deploy/bootstrap
 "$(dirname "${BASH_SOURCE[0]}")/jumpbox"
 
 # deploy WebV after the app starts
-kubectl wait pod -l app=ai-order-accuracy -n ai-order-accuracy --for condition=ready --timeout=60s
+kubectl wait pod -l app=imdb -n imdb --for condition=ready --timeout=60s
 
 kubectl apply -f deploy/webv
-kubectl wait pod -l app=webv-aioa -n ai-order-accuracy --for condition=ready --timeout=30s
